export default [
  {
    id: "respaldo-1",
    title: "Mochila urbana resistente al agua",
    price: 58.9,
    description: "Mochila ligera con compartimento para portátil y bolsillos de acceso rápido.",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=640&q=80",
  },
  {
    id: "respaldo-2",
    title: "Auriculares inalámbricos",
    price: 79.99,
    description: "Auriculares Bluetooth con controles integrados y sonido envolvente.",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=640&q=80",
  },
  {
    id: "respaldo-3",
    title: "Reloj clásico de acero",
    price: 114.5,
    description: "Reloj analógico con caja de acero inoxidable y correa ajustable.",
    category: "jewelery",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=640&q=80",
  },
  {
    id: "respaldo-4",
    title: "Camiseta básica de algodón",
    price: 22.5,
    description: "Camiseta de algodón suave para uso diario.",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=640&q=80",
  },
  {
    id: "respaldo-5",
    title: "Cámara instantánea compacta",
    price: 89.0,
    description: "Cámara compacta para capturar e imprimir recuerdos al instante.",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=640&q=80",
  },
  {
    id: "respaldo-6",
    title: "Gafas de sol estilo clásico",
    price: 36.75,
    description: "Montura ligera de diseño atemporal para el uso diario.",
    category: "jewelery",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=640&q=80",
  },
  {
    id: "respaldo-7",
    title: "Sudadera de algodón orgánico",
    price: 49.9,
    description: "Sudadera cómoda de corte relajado y tejido de algodón.",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=640&q=80",
  },
  {
    id: "respaldo-8",
    title: "Bolso de hombro minimalista",
    price: 64.0,
    description: "Bolso ligero con espacio para los esenciales y cierre seguro.",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=640&q=80",
  },
];
